### ISSUE TITLE
Image by RichMarkdown plugin at last line can't be folded

### ISSUE THREAD

**Issue by graphit0** [ambrt/joplin-plugin-fold-cm#1]
Hey there, thank you for this lovely plugin. It works great except a few minor hiccups which I wanted to document here. 

## Environment
Joplin 1.7.11 (prod, linux)

Client ID: cb04793fca934258829a480063728850
Sync Version: 2
Profile Version: 34
Keychain Supported: No

Revision: f560563 (master)
OS: Lubuntu 20.10 x86_64
Plugin version: 1.2.0

## Preconditions
RichMarkdown plugin installed

## Description
If a link to image resource is placed to last line of the chapter (content below header) and previewed by RichMarkdown plugin, the image stays on page when header is folded.

## Steps

1. Create header
2. Place an image to the last line of the chapter
3. Attempt to fold the header

## Expected behaviour
Header should fold/hide image preview

## Actual behaviour
The image preview stays on page

## Demonstration
https://youtu.be/FV5G38JDnys

**Comment by ambrt** [comment]
I see.
So basically i don't know why this happens (is it RichMarkdown issue or is it folding plugin issue?) but i think
that maybe automatically adding blank space character as last line would be quick work around. 

Thanks for reporting.

**Comment by graphit0** [comment]
I do realize that it might be not Folding plugin issue, yet the integration with Rich Markdown plugin makes particularly Folding plugin "look" like it's misbehaving. In any case, if no fix is planned, I'm fine with it. Moreover, if I were you, I'd not support for integration with any other plugin (with some exceptions) cause that's 'lot of work to keep in touch with every single plugin. 

Although, I imagine, some people might not realize that and hopefully they will read this issue before opening a new one or asking questions why something is not working coupled with something. But again, the purpose of this issue is solely to log the info for the archive and potential issue reporters.

So this issue can be safely closed, thank you for time again

**Comment by ambrt** [comment]
The interoperability of plugins indeed might be managed in a better way on Joplin level (maybe hooks like `afterXYZPlugin`).

Since there are not that many plugins for Joplin i think plugin developers can make manual fixes although you're right that it might end up in kind of maintenance nightmare.  


Basically, an commit,  adds automatically one blank line below image code if next line is header.
The fix looks good on my tests but if you'll find some case where it isn't working then post up.

Thanks for posting
