### ISSUE TITLE
How to install plugin in Windows 10

### ISSUE THREAD

**Issue by joskyday** [ambrt/joplin-plugin-fold-cm#2]
As mentioned in ReadMe file I basically openned windows powershell
unzipped plugin folder.
go to the folder path.
then wrote >>>   npm run dist
however I got 
'webpack' is not recognized as an internal or external command, operable program or batch file.
error. 
The question is: How can I install plugin to windows 10.
By the way you may understand I am new to JavaScript.

**Comment by ambrt** [comment]
Hi, this plugin is already available in Joplin options menu (Tools->Options->Plugins-> Search for plugins: "folding").

For the future: there is releases folder https://github.com/ambrt/joplin-plugin-fold-cm/releases/ that contains ".jpl" file 
which is plugin itself.
You install such file with Tools->Options->Plugins-> Manage your plugins-> Install from file .

**Comment by joskyday** [comment]
Okay, I appreciate thank you.

1 Nis 2021 Per 17:43 tarihinde Rik ***@***.***> şunu yazdı:
